config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages, only: [:create]
  end

  devise_for :users

  root 'rooms#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :user, counter_cache: true, inverse_of: :memberships
  belongs_to :room, counter_cache: true, inverse_of: :members

  validates :user_id, uniqueness: { scope: [:room_id] }
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :room

  default_scope -> { order(:created_at) }
  scope :recent, ->(limit) { last(limit) }

  validates :user_id, :room_id, presence: true
  validates :content, presence: true

  set_callback :create, :after, :post_to_room

  private

  def post_to_room
    room.send_message(:new, attributes, namespace: :message)
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :owner, inverse_of: :rooms, class_name: 'User'
  has_many :members, inverse_of: :room, dependent: :destroy
  has_many :messages, inverse_of: :room, dependent: :destroy

  validates :owner_id, presence: true
  validates :name, presence: true

  def send_message(event, message, opts = {})
    Room.send_message(id, event, message, opts)
  end

  def self.send_message(id, event, message, opts = {})
    WebsocketRails["room_#{id}"].trigger(event, message, opts)
  end

  def send_delayed_message(delay, event, message, opts = {})
    Resque.enqueue_in(delay, DelayedMessageWorker, id, event, message, opts)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable, :confirmable, :lockable, :timeoutable

  has_many :rooms, inverse_of: :owner, foreign_key: :owner_id,
                   dependent: :nullify
  has_many :memberships, inverse_of: :user, class_name: 'Member',
                         dependent: :destroy
  has_many :messages, inverse_of: :user, dependent: :nullify

  validates :name, presence: true

  def joined(room)
    room.send_message(:joined, self, namespace: :user)
  end
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  after_filter :allow_cross_domain, if: :api_request?

  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def api_request?
    request.format == 'json'
  end

  def options
    if request.method == :options
      allow_cross_domain
      render text: '', content_type: 'text/plain', layout: false, template: false
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  private

  def allow_cross_domain
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = %w(OPTIONS GET POST PUT DELETE).join(',')
    headers['Access-Control-Allow-Headers'] = %w(Origin Accept Content-Type X-Requested-With X-CSRF-Token).join(',')
    headers['Access-Control-Max-Age'] = '86400'
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  respond_to :json, only: [:index]

  before_action :load_resource
  authorize_resource

  def index
    respond_with @rooms
  end

  def show
    respond_with @room
  end

  def new
    respond_with @room
  end

  def edit
    respond_with @room
  end

  def create
    @room.save
    respond_with @room
  end

  def update
    @room.update_attributes(permitted_params)
    respond_with @room
  end

  def destroy
    @room.destroy
    respond_with @room, location: rooms_path
  end

  private

  def load_resource
    case params[:action].to_sym
    when :index
      @rooms = Room.accessible_by(current_ability)
    when :new
      @room = Room.new
    when :create
      @room = current_user.rooms.build(permitted_params)
    else
      @room = Room.find(params[:id])
    end
  end

  def permitted_params
    params.require(:room).permit(:name, :description)
  end
end

app/controllers/sockets/authorization_controller.rb
module Sockets
  class AuthorizationController < WebsocketRails::BaseController
    def authorize_channels
      @room = Room.find(params[:room_id])
      @user = User.first
      channel = WebsocketRails[message[:channel]]

      # if can? :subscribe, channel
      accept_channel @user
      @user.joined(@room)
      # else
      #   deny_channel({:message => 'authorization failed!'})
      # end
    end
  end
end

app/controllers/sockets/clients_controller.rb
module Sockets
  class ClientsController < WebsocketRails::BaseController
    before_filter :find_room

    def connected
      unless WebsocketRails["room_#{@room.id}"].is_private?
        WebsocketRails["room_#{@room.id}"].make_private
      end
    end

    def disconnected
    end

    private

    def find_room
      @room = Room.find(params[:room_id]) if params[:room_id]
    end
  end
end

app/controllers/sockets/messages_controller.rb
module Sockets
  class MessagesController < WebsocketRails::BaseController
    def create
      @room = Room.find(params[:room_id])
      @message = @room.messages.build({ content: message, user_id: User.first.id })

      if @message.save
        trigger_success({ message: @message.to_json, status: 200 })
      else
        trigger_failure({ message: @message.to_json, status: 400 })
      end
    end
  end
end

app/controllers/sockets/users_controller.rb
module Sockets
  class UsersController < WebsocketRails::BaseController
    def joined
      @room = Room.find(params[:room_id])
      User.find(message).joined(@room)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(title, opts = {})
    title = [title].flatten

    content_for :title do
      title.join(' &raquo; ').html_safe
    end
  end

  def flash_messages(opts = {})
    [:notice, :success, :info, :error, :alert, :warning].collect do |key|
      unless flash[key].blank? || !flash[key].is_a?(String)
        style = key
        style = :info if key == :notice
        style = :danger if key == :alert
        style = :danger if key == :error
        opts[:style] ||= ""
        opts[:style] += " alert-#{style}"
        opts[:style].strip!
        opts[:message] = flash[key]
        render('application/flash_message', opts)
      end
    end.join
  end

  def main_width_class
    if content_for?(:sidebar_left)
      'col-md-9'
    else
      'col-md-12'
    end
  end

  def element_for(model, tag = :article, opts = {}, &block)
    if tag.is_a?(Hash)
      opts = tag
    else
      opts[:tag] = tag
    end

    tag = opts.delete(:tag) || :article

    opts[:class] = [opts[:class]].flatten || []
    opts[:class] << 'object'
    opts[:class] << model.class.name.underscore
    opts[:class] = opts[:class].compact.join(' ')

    opts[:id] ||= dom_id(model)

    opts[:data] ||= {
      id: model.id,
      type: model.class.name.underscore
    }

    content_tag(tag, opts) do
      yield
    end
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def menu_link_to(label, path, options = {})
    exact_path = options.delete(:exact_path) || false
    element = options.delete(:element) || :li

    link = link_to raw(label), path, options

    if exact_path
      css_class = request.path == path ? 'active' : nil
    else
      css_class = request.path =~ /^#{path}/ ? 'active' : nil
    end

    content_tag element, link, class: css_class
  end
end

app/views/application/_flash_message.html.slim
- unless message.blank?
  .row
    .col-xs-12
      div class="alert fade in #{style}"
        a.close data-dismiss="alert" &times;
        == message

app/views/application/_footer.html.slim
footer#main
  .container
    p.text-center.text-muted
      span.hidden-xs= t('.text.terms')
      br
      small= t('.label.copyright')

app/views/application/_html_header.html.slim
meta charset="utf-8"
meta http-equiv="X-UA-Compatible" content="IE=9"
meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"

title
  | Chatter
  - if content_for?(:title)
    == " &raquo; #{yield :title}"

= stylesheet_link_tag 'application', media: 'all', :'data-turbolinks-track' => true

/[ if lt IE 9 ]
  = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/respond.js/1.2.0/respond.js'
= javascript_include_tag 'application', :'data-turbolinks-track' => true
= javascript_include_tag :modernizr

link href=asset_path('favicon.ico') type="image/x-icon" rel="shortcut icon"/
link href=asset_path('apple-touch-icon-precomposed.png') rel="apple-touch-icon" /
link href=asset_path('apple-touch-icon-72x72-precomposed.png') sizes="72x72" rel="apple-touch-icon"/
link href=asset_path('apple-touch-icon-76x76-precomposed.png') sizes="76x76" rel="apple-touch-icon"/
link href=asset_path('apple-touch-icon-114x114-precomposed.png') sizes="114x114" rel="apple-touch-icon"/
link href=asset_path('apple-touch-icon-120x120-precomposed.png') sizes="120x120" rel="apple-touch-icon"/
link href=asset_path('apple-touch-icon-144x144-precomposed.png') sizes="144x144" rel="apple-touch-icon"/
link href=asset_path('apple-touch-icon-152x152-precomposed.png') sizes="152x152" rel="apple-touch-icon"/

= csrf_meta_tags

== yield :header

app/views/application/_navigation.html.slim
nav.navbar.navbar-default.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      button.navbar-toggle data-target="#main-nav" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        / = image_tag 'logo.svg', class: 'img-logo'
        small= t('app.name')
    #main-nav.collapse.navbar-collapse
      ul.nav.navbar-nav
        / = menu_link_to t('.label.chains'), chains_path
        / = menu_link_to t('.label.venues'), venues_path
        / = menu_link_to t('.label.about'), '#'
        / = menu_link_to t('.label.categories'), categories_path
        / = menu_link_to t('.label.explore_views'), explore_views_path
        / = menu_link_to t('.label.licensors'), licensors_path
        / = menu_link_to t('.label.users'), users_path
      / ul.nav.navbar-nav.navbar-right
      /   - if user_signed_in?
      /     li.dropdown
      /       a href="#" class="dropdown-toggle" data-toggle="dropdown"
      /         / = current_user.name
      /         = ' '
      /         span.caret
      /       / ul.dropdown-menu role="menu"
      /         / li= link_to t('.label.log_off'), destroy_user_session_path, method: :delete
      /   - else
      /     = menu_link_to t('.label.sign_in'), new_user_session_path
      /     = menu_link_to t('.label.sign_up'), new_user_registration_path

app/views/application/_no_results.html.slim
p.text-center.text-muted= t('.text.no_results')

app/views/layouts/application.html.slim
doctype 5

/[ if lt IE 7 ]
    html class="no-js ie6 ie" lang=I18n.locale
/[ if IE 7 ]
    html class="no-js ie7 ie" lang=I18n.locale
/[ if IE 8 ]
    html class="no-js ie8 ie" lang=I18n.locale
/[ if (gt IE 9)|!(IE) ]
    html class="no-js" lang=I18n.locale

head
  = render 'html_header'

body data-language=I18n.locale data-controller=params[:controller].parameterize data-action=params[:action].parameterize
  = render 'navigation'

  - if content_for?(:page_header)
    .container-fluid#page-header-wrapper
      .container
        .row
          .col-xs-12
            .page-header
              == yield :page_header

  .container
    .row
      section.col-xs-12 role="main"
        == flash_messages
        == yield

  = render 'footer'

app/views/rooms/_room.html.slim
- present room do |presented|
  = element_for room, { class: 'row' }
    .col-xs-6.col-md-3
      .thumbnail
        .caption
          h3= link_to room.name, room
          = presented.description

app/views/rooms/index.html.slim
- title t('.title')

- content_for :page_header do
  h1
    = t('.page_header')

.row
  .col-xs-12#main
    - if @rooms.any?
      = render partial: 'rooms/room', collection: @rooms, as: :room
    - else
      = render partial: 'no_results'

app/views/rooms/show.html.slim
- title [t('.title'), @room.name]

- content_for :page_header do
  h1
    = @room.name
    small= t('.page_header')

.row
  .col-xs-12.col-md-8#main data-behavior="chat" data-room-id=@room.id
    .form-group.text
      = text_area_tag 'messages', '', disabled: true, rows: 20, class: 'text form-control'
    = simple_form_for :message, url: room_messages_path(@room) do |f|
      = f.input :content, input_html: { autocomplete: 'off' }
  aside.col-xs-12.col-md-4